const mongoose=require("mongoose")

const orderSchema=new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        city:{type:String,required:true},
        state:{type:String,required:true},
        country:{type:String,required:true},
        pincode:{type:Number,required:true},
        phone:{type:Number,required:true},
    },

    orderItems:[{
        name:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
        quantity:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        _id:{
            type:mongoose.Schema.ObjectId,
            ref:"_id",
            required:true
        }
    }],
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"User",
        required:true
    },
    paymentInfo:{
        id:{
            type:String,
            required:true 
        },
        status:{
            type:String,
            required:true 
        },
    },
    paidAt:{
        type:Date,
        required:true 
    },
    itemsPrice:{
        type:Number,
       default:0
    },
    taxPrice:{
        type:Number,
       default:0
    },
    shippingPrice:{
        type:Number,
       default:0
    },
    totalPrice:{
        type:Number,
       default:0
    },
    orderStatus:{
        type:String,
       required:true,
       default:"Order Placed"
    },
    deliveredAt:Date,
    createdAt:{
        type:Date,
       default:Date.now()
    }
})

module.exports=mongoose.model("Order",orderSchema)